#!/bin/bash -eu

build_recursive_index() {
	local wd="$(pwd)"
	local title="${wd#${root_dir}}"
	echo '<html><body><h1>'"${title:-/}"'</h1><ul>' > index.html
	echo '  <li><a href="..">..</a>' >> index.html
	for f in *; do
		[[ "$f" = "index.html" ]] && continue
		if [[ -d "$f" ]]; then
			(cd "$f"; build_recursive_index)
			f="${f}/"
		fi
		echo '  <li><a href="./'"$f"'">'"$f"'</li>' >> index.html
	done
	echo '</ul></body></html>' >> index.html
}

cd maven
root_dir="$(pwd)"

build_recursive_index
